language: node_js
node_js:
  - "11.9"
install:
  - npm install
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
script:
  - grunt dev_public_beta
after_script:
  - grunt deploy_dev_public_beta
