language: node_js

node_js:
  - "11.9"

cache:
  - npm

addons:
  apt:
    packages:
    - sshpass
    
before_install:
  - openssl aes-256-cbc -K $deploy_key_aes_key -iv $deploy_key_aes_iv
    -in deploy_key.enc -out ./deploy_key -d
  - chmod 600 ./deploy_key

install:
  - npm install
  - if [ "$TRAVIS_BRANCH" = "development" ] || [ "$TRAVIS_BRANCH" = "webpack" ]; then
      npm run build -- --mode=development --constants development --public=${PUBLIC_PATH};
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      npm run build -- --mode=production --constants production --public=${PUBLIC_PATH};
    fi
  - mv ./dist/index.html ./index.html

deploy:
  - provider: script
    script: sshpass -p${KBHKILDER_SSH_PASSWORD} scp -o LogLevel=Verbose -o StrictHostKeyChecking=no -r ./dist/* ${KBHKILDER_SSH_USER}@${KBHKILDER_SSH_HOST}:${KBHKILDER_SSH_PATH}
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|development|webpack)$
     
  - provider: script
    script: scp -i ./deploy_key -o LogLevel=Verbose -o StrictHostKeyChecking=no -P ${KBHARKIV_SSH_PORT} ./index.html ${KBHARKIV_SSH_USER}@${KBHARKIV_SSH_HOST}:${KBHARKIV_SSH_PATH}
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^(master|development|webpack)$"